server:
  port: 8010
spring:
  application:
    name: woniu-service

  profiles:
    active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: rjx666nxx
      timeout: 5000
#  redis:
#    host: 127.0.0.1
#    password: rjx666nxx
